# Generated by Django 6.0.2 on 2026-02-20 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('building', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(default=60)),
                ('room_type', models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Computer Lab'), ('seminar', 'Seminar Room'), ('tutorial', 'Tutorial Room')], default='lecture', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('subjects', models.TextField(help_text='Comma-separated list of subjects this faculty can teach')),
                ('max_hours', models.PositiveIntegerField(default=20, help_text='Max teaching hours per week')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('hours_required', models.PositiveIntegerField(default=4, help_text='Weekly hours required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduler.faculty')),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('solver_status', models.CharField(blank=True, max_length=50)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Currently displayed timetable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('period', models.PositiveIntegerField(help_text='Period number (1-8)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('day', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.faculty')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.timeslot')),
            ],
            options={
                'ordering': ['timeslot__day', 'timeslot__period'],
                'unique_together': {('classroom', 'timeslot', 'schedule_version'), ('faculty', 'timeslot', 'schedule_version')},
            },
        ),
        migrations.CreateModel(
            name='WorkloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_version', models.PositiveIntegerField(default=1)),
                ('assigned_hours', models.PositiveIntegerField(default=0)),
                ('max_hours', models.PositiveIntegerField(default=0)),
                ('utilization_percent', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_logs', to='scheduler.faculty')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('faculty', 'schedule_version')},
            },
        ),
    ]
